### PR TITLE
Add doc on how to use ruleset from Spectral

### PR DESCRIPTION
**Pull request by mikekistler**
This PR adds doc to README on how to use the Spectral rulesets with the Spectral CLI and VSCode extension.

I also made some small fixes to the CONTRIBUTING.md.

### CODE REVIEW

**Comment by mikekistler** [comment]
@jianyexi Can you help with the doc for using the Spectral rulesets from the Spectral CLI? I'm not quite clear which file we should point to. The ruleset files in `packages/rulesets/src/spectral` are TypeScript files, and Spectral won't take these, and it looks like `dist` is excluded from the repo.

**Comment by jianyexi** [comment]
I put the js ruleset  into  https://github.com/Azure/azure-openapi-validator/tree/develop/packages/rulesets/generated/spectral,

**Comment by jianyexi** [comment]
@mikekistler I've bypassed the spectral issue by converting the ruleset file to es module, it works now

**Review by jianyexi — APPROVED** [review]

**Comment by jianyexi** [comment]
looks great

**Pull request merged**
