### PR TITLE
Handling empty operationIds in validation rules

### PR DESCRIPTION
**Pull request by dsgouda**
Addresses https://github.com/Azure/azure-openapi-validator/issues/83
- Ensuring we check operationId for null values in val rules
- Modifying OperationNameValidation to flag empty operationIds (To come up with better messaging we may have to write a new validation rule)

### CODE REVIEW

**Comment by veronicagg** [comment]
Oh, and this PR included the commits from your other PR, so you may need to merge that one first.

**Comment by dsgouda** [comment]
AutoRest simply informs it failed to generate code.

**Comment by olydis** [comment]
@dsgouda why is this PR completely empty?

**Comment by dsgouda** [comment]
Probably shouldn't have merged this, this got stamped over by https://github.com/Azure/azure-openapi-validator/commit/536c1169d6947f1de56aa4c1fb2e35af7bc136d8
I will just let this be the link so we have a reference

**Comment by olydis** [comment]
ah yes, that's helpful, thanks!

**Pull request merged**
